### ISSUE TITLE
@Scripts热更文件夹下代码也会打入主工程嘛？

### ISSUE THREAD

**Issue by EricDDK** [jinglikeblue/Zero#31]

**Comment by jinglikeblue** [comment]
会！如果不想打包到主工程，可以在打包时将该目录剪切出来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eric.Ding"<notifications@github.com&gt;; 
发送时间: 2020年1月16日(星期四) 下午2:54
收件人: "jinglikeblue/Zero"<Zero@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [jinglikeblue/Zero] @Scripts热更文件夹下代码也会打入主工程嘛？ (#31)

**Comment by EricDDK** [comment]
> 会！如果不想打包到主工程，可以在打包时将该目录剪切出来
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Eric.Ding"<notifications@github.com&gt;; 发送时间: 2020年1月16日(星期四) 下午2:54 收件人: "jinglikeblue/Zero"<Zero@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [jinglikeblue/Zero] @scripts热更文件夹下代码也会打入主工程嘛？ (#31) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，谢谢~
